#!/usr/bin/env python3
"""Generate compose.override.yml to inject h2c-api into a compose stack.

Reads compose.yml, generates self-signed certs + dummy SA token,
and writes a compose.override.yml that adds h2c-api as a service
and mounts the fake ServiceAccount into every existing service.

Usage:
    python3 h2c_inject.py [compose.yml]
"""

import subprocess
import sys
from pathlib import Path

import yaml

SA_DIR = "h2c-sa"
SA_MOUNT = "/var/run/secrets/kubernetes.io/serviceaccount"


def generate_sa(sa_dir, namespace):
    """Generate self-signed cert, dummy token, namespace file."""
    sa_dir.mkdir(exist_ok=True)

    if not (sa_dir / "tls.crt").exists():
        san = "DNS:h2c-api,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc"
        subprocess.run([
            "openssl", "req", "-x509", "-newkey", "rsa:2048",
            "-keyout", str(sa_dir / "tls.key"),
            "-out", str(sa_dir / "tls.crt"),
            "-days", "3650", "-nodes",
            "-subj", "/CN=h2c-api",
            "-addext", f"subjectAltName={san}",
        ], check=True, capture_output=True)
        # self-signed: ca.crt = tls.crt
        (sa_dir / "ca.crt").write_bytes((sa_dir / "tls.crt").read_bytes())
        print("  certs: generated", file=sys.stderr)
    else:
        print("  certs: reusing existing", file=sys.stderr)

    (sa_dir / "token").write_text("h2c-api-dummy-token", encoding="utf-8")
    (sa_dir / "namespace").write_text(namespace, encoding="utf-8")


def main():
    """Read compose.yml, generate SA certs, write compose.override.yml."""
    compose_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("compose.yml")
    if not compose_path.exists():
        print(f"Error: {compose_path} not found", file=sys.stderr)
        sys.exit(1)

    with open(compose_path, encoding="utf-8") as f:
        compose = yaml.safe_load(f)

    project_name = compose.get("name", "default")
    services = compose.get("services", {})
    sa_dir = Path(SA_DIR)

    generate_sa(sa_dir, project_name)

    # --- Build compose.override.yml ---
    override_services = {}

    # h2c-api service
    h2c_volumes = [
        f"./{SA_DIR}:{SA_MOUNT}:ro",
        f"./{compose_path}:/data/compose.yml:ro",
    ]
    for d in ("configmaps", "secrets"):
        if (compose_path.parent / d).is_dir():
            h2c_volumes.append(f"./{d}:/data/{d}:ro")

    override_services["h2c-api"] = {
        "image": "docker.io/baptisterajaut/h2c-api:latest",
        "restart": "unless-stopped",
        "volumes": h2c_volumes,
    }

    # Inject SA mount + env into every existing service
    for svc_name in services:
        override_services[svc_name] = {
            "volumes": [f"./{SA_DIR}:{SA_MOUNT}:ro"],
            "environment": {
                "KUBERNETES_SERVICE_HOST": "h2c-api",
                "KUBERNETES_SERVICE_PORT": "6443",
            },
        }

    override = {"services": override_services}

    override_path = compose_path.parent / "compose.override.yml"
    with open(override_path, "w", encoding="utf-8") as f:
        f.write("# Generated by h2c-api — do not edit\n")
        yaml.dump(override, f, default_flow_style=False, sort_keys=False)

    print(f"Generated {override_path}", file=sys.stderr)
    print(f"  services injected: {len(services)}", file=sys.stderr)
    print(f"  SA mount: ./{SA_DIR}/ -> {SA_MOUNT}", file=sys.stderr)
    print(f"  namespace: {project_name}", file=sys.stderr)


if __name__ == "__main__":
    main()
